resources:
  - ../../base

buildMetadata:
  - originAnnotations

components:
  - ../../components/app
  - ../../components/ingress
  - ../../components/keyvault
  - ../../components/network

patchesStrategicMerge:
  - deployment.yaml
  - ingress.yaml

commonLabels:
  generator: kustomize
  team: cccssront01
  app: sensorenregister
  env: dev

replicas:
  - name: app
    count: 3

patches:
  - target:
      kind: Ingress
      name: app
    patch: |-
      - op: add
        path: "/spec/rules/0/host"
        value: ssr-o.azure.amsterdam.nl

images:
  - name: localhost:5000/sensorenregister/api
    newName: mainweuacroyh7oqq4sbyjt.azurecr.io/sensorenregister/api-dev
    newTag: latest
    # newTag: plain-text

replacements:
  - source:
      kind: Deployment
      name: app
      fieldPath: spec.template.spec.tolerations
    targets:
      - select:
          kind: Job
          labelSelector: component=api
        fieldPaths:
          - spec.template.spec.tolerations
        options:
          create: true
