resources:
  - ../../base

buildMetadata:
  - originAnnotations

components:
  - ../../components/api
  - ../../components/admin
  - ../../components/keyvault
  - ../../components/network

patchesStrategicMerge:
  - secretproviderclass.yaml

commonLabels:
  team: cccssront01
  app: sensorenregister
  env: dev

replicas:
  - name: api
    count: 1

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: "/spec/template/spec/tolerations"
        value:
          - key: "cccssront01"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"

  - target:
      kind: Ingress
    patch: |-
      - op: add
        path: "/spec/rules/0/host"
        value: ssr-o.azure.amsterdam.nl
      - op: replace
        path: "/spec/tls/0/hosts"
        value: 
          - ssr-o.azure.amsterdam.nl

  - target:
      kind: Ingress
      name: api
    patch: |-
      - op: replace
        path: "/spec/ingressClassName"
        value: nginx-internal

  - target:
      kind: Ingress
      name: admin
    patch: |-
      - op: replace
        path: "/spec/ingressClassName"
        value: nginx-internal

images:
  - name: localhost:5001/sensorenregister/api
    newName: mainweuacroyh7oqq4sbyjt.azurecr.io/sensorenregister/api-dev
    newTag: latest

replacements:
  - source:
      kind: Deployment
      name: api
      fieldPath: spec.template.spec.tolerations
    targets:
      - select:
          kind: Job
        fieldPaths:
          - spec.template.spec.tolerations
        options:
          create: true
      - select:
          kind: CronJob
        fieldPaths:
          - spec.jobTemplate.spec.template.spec.tolerations
        options:
          create: true
