bases:
  - ../../base

commonLabels:
  env: dev

patchesStrategicMerge:
  - deployment.yaml
  - ingress.yaml

patches:
  - target:
      kind: Ingress
      name: app
    patch: |-
      - op: add
        path: "/spec/rules/0/host"
        value: api.dev.sensorenregister.amsterdam.nl
