apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

buildMetadata:
  - originAnnotations

components:
  - ../../components/api
  - ../../components/admin
  - ../../components/keyvault
  - ../../components/network

labels:
  - includeselectors: true
    pairs:
      app: sensorenregister
      env: dev
      team: cccssront01

commonLabels:
  team: cccssront01
  app: sensorenregister
  env: dev

replicas:
  - name: api
    count: 1

configMapGenerator:
  - name: api-env
    behavior: merge
    literals: &api-env
      - AZURE_KEY_VAULT=https://application-o-gp4jqffo3h.vault.azure.net/
      - MANAGED_IDENTITY_CLIENTID=00d77036-c127-4b38-a581-f170b55d65f0
  - name: admin-env
    behavior: merge
    literals: *api-env

patches:
  - path: secretproviderclass.yaml

  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: "/spec/template/spec/tolerations"
        value:
          - key: "cccssront01"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"

  - target:
      kind: Ingress
    patch: |-
      - op: add
        path: "/spec/rules/0/host"
        value: ssr-o.azure.amsterdam.nl
      - op: replace
        path: "/spec/tls/0/hosts"
        value: 
          - ssr-o.azure.amsterdam.nl

  - target:
      kind: Ingress
      name: api
    patch: |-
      - op: replace
        path: "/spec/ingressClassName"
        value: nginx-internal

  - target:
      kind: Ingress
      name: admin
    patch: |-
      - op: replace
        path: "/spec/ingressClassName"
        value: nginx-internal

replacements:
  - source:
      kind: Deployment
      name: api
      fieldPath: spec.template.spec.tolerations
    targets:
      - select:
          kind: Job
        fieldPaths:
          - spec.template.spec.tolerations
        options:
          create: true
      - select:
          kind: CronJob
        fieldPaths:
          - spec.jobTemplate.spec.template.spec.tolerations
        options:
          create: true
