resources:
  - ../../base

commonLabels:
  env: dev

components:
  - ../../components/app
  - ../../components/ingress
  - ../../components/keyvault

patchesStrategicMerge:
  - ingress.yaml

patches:
  - target:
      kind: Ingress
      name: app
    patch: |-
      - op: add
        path: "/spec/rules/0/host"
        value: ssr-o.azure.amsterdam.nl

images:
  - name: localhost:5000/sensorenregister/api
    newName: mainweuacroyh7oqq4sbyjt.azurecr.io/sensorenregister/api
    newTag: latest
    # newTag: plain-text
