apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets
spec:
  provider: azure
  parameters:
    userAssignedIdentityID: "00d77036-c127-4b38-a581-f170b55d65f0"
    keyvaultName: main-weu-o-yh7oqq4sbyjt
    tenantId: "72fca1b1-2c2e-4376-a445-294d80196804" # The tenant ID of the key vault
