apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: main
          image: nginxdemos/hello
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 1
              memory: "64Mi"
            limits:
              cpu: 1
              memory: "64mi"
          envFrom:
            - configMapRef:
                name: app-env
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - name: config
          configMap:
            name: app-config
