commonLabels:
  app: sensorenregister
  env: base

labels:
  - pairs:
      team: TAMM
    includeSelectors: false
    includeTemplates: true

configMapGenerator:
  - name: app-env
    envs:
      - app.env
  - name: app-config
    files:
      - app.ini

# Copy some fields from the deployments to the jobs
replacements:
  - source:
      kind: Deployment
      name: app
      fieldPath: spec.template.spec.containers.[name=main].envFrom
    targets:
      - select:
          kind: Job
          name: migrate
        fieldPaths:
          - spec.template.spec.containers.[name=main].envFrom
        options:
          create: true
      - select:
          kind: Job
          name: import
        fieldPaths:
          - spec.template.spec.containers.[name=main].envFrom
        options:
          create: true

  - source:
      kind: Deployment
      name: app
      fieldPath: spec.template.spec.containers.[name=main].volumeMounts
    targets:
      - select:
          kind: Job
          name: migrate
        fieldPaths:
          - spec.template.spec.containers.[name=main].volumeMounts
        options:
          create: true
      - select:
          kind: Job
          name: import
        fieldPaths:
          - spec.template.spec.containers.[name=main].volumeMounts
        options:
          create: true

  - source:
      kind: Deployment
      name: app
      fieldPath: spec.template.spec.volumes
    targets:
      - select:
          kind: Job
          name: migrate
        fieldPaths:
          - spec.template.spec.volumes
        options:
          create: true
      - select:
          kind: Job
          name: import
        fieldPaths:
          - spec.template.spec.volumes
        options:
          create: true

resources:
  - configmap.yaml
  - migrate.job.yaml
  - import.job.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - secretproviderclass.yaml
