keyVaultName: ssr-o-gp4jqffo3heda
keyVaultIdentity: 00d77036-c127-4b38-a581-f170b55d65f0

image:
  repository: sensorenregister/api-dev

nodepool: cccssront01
host: ssr-o.azure.amsterdam.nl

env:
  AZURE_KEY_VAULT: "https://ssr-o-gp4jqffo3heda.vault.azure.net/"
  AZURE_MANAGED_IDENTITY_CLIENTID: 00d77036-c127-4b38-a581-f170b55d65f0

secrets:
  keyvault:
    certificate:
      keyVaultName: shared-o-ftytfsr6vuduo
