#!/bin/env bash

COMMAND="\e[92m"
HEADER="\e[96m"
COMMENT="\e[33m"
ENDCOLOR="\e[0m"

function header () {
  echo -e "${HEADER}$*${ENDCOLOR}"
  echo "------------------------------------"
  echo ""
}

function comment () {
  echo -e "${COMMENT}$*${ENDCOLOR}"
}

function run () {
  echo -e "> ${COMMAND}$*${ENDCOLOR}"
  read -r
  trap "echo " EXIT INT TERM
  bash -c "$*"
  trap - EXIT INT TERM
  echo ""
}

run docker-compose build dev
run docker image ls localhost:5000/iothings-dev:latest
run docker-compose push dev
run tree manifests
run "kustomize build manifests/overlays/local | bat -l yaml"
run "kustomize build manifests/overlays/local | kubectl apply -f -"
run kubectl get pod,deploy,svc,job,ingress
run stern .
run kubectl get pod,deploy,svc,job,ingress
run xdg-open http://localhost/iothings
run stern .
