version: "3.5"

x-app: &base-app
  build:
    context: .
    target: app
  depends_on:
    - database
  environment: &base-app-env
    SECRET_KEY: "insecure"
    DEBUG: "true"
    OIDC_RP_CLIENT_ID:
    OIDC_RP_CLIENT_SECRET:
  volumes:
    - ./src:/app/src
    - ./tests:/app/tests
    - ./deploy:/app/deploy
  entrypoint: /app/deploy/wait-for-it.sh database:5432 --

volumes:
  db_data:

services:
  database:
    image: amsterdam/postgres11
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      PGDATA: /data
    volumes:
      - db_data:/data

  app:
    <<: *base-app
    build:
      context: .
      target: app
      args:
        - BUILD_DATE
        - BUILD_REVISION
        - BUILD_VERSION
    image: docker-registry.data.amsterdam.nl/datapunt/iothings-api:${VERSION:-latest}
    command: /app/deploy/docker-run.sh
    environment:
      <<: *base-app-env
      DEBUG: "false"

  dev:
    <<: *base-app
    build:
      context: .
      target: dev
    command: python manage.py runserver_plus --print-sql 0.0.0.0:8000

  test:
    <<: *base-app
    build:
      context: .
      target: tests
    environment:
      <<: *base-app-env
      DJANGO_SETTINGS_MODULE: "iot.settings.settings"
      OIDC_RP_CLIENT_ID: tests
      OIDC_RP_CLIENT_SECRET: tests
