version: '3.5'

x-app: &base-app
  build:
    context: .
    target: app
  depends_on:
    - database
  volumes:
    - ./src:/app/src
    - ./tests:/app/tests
    - ./deploy:/app/deploy
  entrypoint: /app/deploy/wait-for-it.sh database:5432 --

volumes:
  db_data:

services:
  database:
    image: amsterdam/postgres11
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      PGDATA: /data
    volumes:
      - db_data:/data

  app:
    <<: *base-app
    build:
      context: .
      target: app
      args:
        - BUILD_DATE
        - BUILD_REVISION
        - BUILD_VERSION
    image: docker-registry.data.amsterdam.nl/datapunt/iot-api:${VERSION:-latest}
    command: /app/deploy/docker-run.sh
    environment:
      DEBUG: "false"

  dev:
    <<: *base-app
    build:
      context: .
      target: dev
    command: python manage.py runserver 0.0.0.0:8001
    environment:
      DEBUG: "true"

  test:
    <<: *base-app
    build:
      context: .
      target: tests
    environment:
      DEBUG: "true"
      DJANGO_SETTINGS_MODULE: "iot.settings.settings"
      OIDC_RP_CLIENT_ID: "x"
      OIDC_RP_CLIENT_SECRET: "x"
