version: "3.5"

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400

x-app: &base-app
  build:
    context: .
    target: app
  environment: &base-app-env
    SECRET_KEY: "insecure"
    ADMIN_ENABLED: "true"
    API_ENABLED: "true"
    DEBUG: "true"
    PYTHONBREAKPOINT:
    SENTRY_DSN:
    OIDC_BASE_URL:
    OIDC_RP_CLIENT_ID:
    OIDC_RP_CLIENT_SECRET:
    APPLICATIONINSIGHTS_CONNECTION_STRING:
    DATABASE_HOST: database
    DATABASE_USER: dev
    DATABASE_NAME: dev
    DATABASE_PASSWORD: dev
  volumes:
    - ./src:/app/src
    - ./tests:/app/tests
    - ./deploy:/app/deploy
    - cache:/home/app/.azure
    - ./pyproject.toml:/app/pyproject.toml
  entrypoint: /app/deploy/wait-for-it.sh database:5432 --
  depends_on:
    database:
      condition: service_healthy

volumes:
  db_data:
  cache:

services:
  database:
    image: postgis/postgis:14-3.3
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      PGDATA: /data
    volumes:
      - db_data:/data
    healthcheck:
      test: pg_isready -U dev -d dev
      interval: 10s
      timeout: 1s
      retries: 5

  app: &app
    <<: *base-app
    build:
      context: .
      target: app
    image: ${REGISTRY:-localhost:5000}/${REPOSITORY:-sensorenregister/api}:${VERSION:-latest}
    command: /app/deploy/docker-run.sh
    environment:
      <<: *base-app-env
      # DEBUG: "false"
    healthcheck:
      test: curl -f http://localhost:8000/status/health
      interval: 10s
      timeout: 1s
      retries: 5

  dev:
    <<: *base-app
    image: ${REGISTRY:-localhost:5000}/${REPOSITORY:-sensorenregister/api}-dev:${VERSION:-latest}
    build:
      context: .
      target: dev
    environment:
      <<: *base-app-env
      DJANGO_SETTINGS_MODULE: "iot.settings"
    command: "./manage.py runserver 0.0.0.0:8000"

  test:
    <<: *base-app
    image: ${REGISTRY:-localhost:5000}/${REPOSITORY:-sensorenregister/api}-test:${VERSION:-latest}
    build:
      context: .
      target: tests
    environment:
      <<: *base-app-env
      DJANGO_SETTINGS_MODULE: "iot.settings"
      OIDC_RP_CLIENT_ID: tests
      OIDC_RP_CLIENT_SECRET: tests
      DATABASE_HOST: database
      DATABASE_USER: dev
      DATABASE_NAME: dev
      DATABASE_PASSWORD: dev
