[tool.black]
# Default is 88
line-length = 88
# Black will default to double quotes
skip-string-normalization = true
exclude = 'migrations|urls.py|tests|settings.py'

[tool.pytest.ini_options]
addopts = "-v -s --ff --nf --cov --cov-report term-missing --cov-config /app/pyproject.toml"

[tool.isort]
profile = "black"
src_paths = ["src", "tests"]
skip = "migrations"

[tool.coverage.run]
source = ["/app/src"]
omit = [
    "/app/tests",
    "/app/src/manage.py",
    "/app/src/main/asgi.py",
    "/app/src/main/wsgi.py",
    "/app/src/main/settings.py",
    "/app/src/main/urls.py",
    "/app/src/iot/urls.py",
    "*/migrations/*"
]

[tool.coverage.report]
fail_under = 80
skip_covered = true
show_missing = true
sort = "Cover"