# Generated by Django 2.2.7 on 2019-11-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0007_change_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='categories',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
