# Generated by Django 3.2.9 on 2021-11-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0009_introduce_new_models_loosely_based_on_sensrnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person2',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
