# Generated by Django 3.2.9 on 2021-11-25 11:20

import logging

import django.contrib.gis.db.models.fields
from django.db import migrations, models

import django.contrib.postgres.fields.citext
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations, models, ProgrammingError
import django.db.models.deletion


logger = logging.getLogger(__name__)


def clean_whitespace(apps, schema_editor):

    Theme = apps.get_model('iot', 'Theme')
    for theme in Theme.objects.all():
        theme.name = theme.name.strip()
        theme.save()

    Person2 = apps.get_model('iot', 'Person2')
    for person in Person2.objects.all():
        person.name = person.name.strip()
        person.email = person.email.strip()
        person.telephone = person.telephone.strip()
        person.organisation = person.organisation.strip()
        if person.website is not None:
            person.website = person.website.strip()
        person.save()

    LegalGround = apps.get_model('iot', 'LegalGround')
    for legal_ground in LegalGround.objects.all():
        legal_ground.name = legal_ground.name.strip()
        legal_ground.save()

    Type2 = apps.get_model('iot', 'Type2')
    for type in Type2.objects.all():
        type.name = type.name.strip()
        type.save()

    Region = apps.get_model('iot', 'Region')
    for region in Region.objects.all():
        region.name = region.name.strip()
        region.save()

    Device2 = apps.get_model('iot', 'Device2')
    for device in Device2.objects.all():
        device.reference = device.reference.strip()
        if device.location_description is not None:
            device.location_description = device.location_description.strip()
        device.datastream = device.datastream.strip()
        device.observation_goal = device.observation_goal.strip()
        if device.privacy_declaration is not None:
            device.privacy_declaration = device.privacy_declaration.strip()
        device.save()


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0010_theme_is_other'),
    ]

    operations = [
        migrations.RunPython(clean_whitespace),
    ]
