# Generated by Django 3.2.9 on 2022-05-17 11:57

import django.contrib.postgres.fields
from django.db import migrations, models


def make_many_projects(apps, schema_editor):
    """
    Adds the Device2 Owner's organisation object in device2.projects. So by
    default all the projects will have a default path which is the organisation name
    of the device's owner. 
    """
    Device2 = apps.get_model('iot', 'Device2')
    Project = apps.get_model('iot', 'Project')

    for device2 in Device2.objects.all():
        result = Project.objects.get_or_create(
            path=[device2.owner.organisation])[0]
        device2.projects.add(result)


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0011_new_model_observation_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Organisation name'), size=None)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects'
            },
        ),
        migrations.AddField(
            model_name='device2',
            name='projects',
            field=models.ManyToManyField(to='iot.Project', verbose_name='Projects'),
        ),
        migrations.RunPython(
            make_many_projects, 
            reverse_code=None
        ),
    ]
