# Generated by Django 3.2.13 on 2022-06-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0012_new_model_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person2',
            name='website',
            field=models.TextField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
