apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: main
          volumeMounts:
            - mountPath: /secrets
              $patch: delete
      volumes:
        - name: secrets
          $patch: delete
