apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

components:
- ../../components/api
- ../../components/admin
- ../../components/database

commonLabels:
  app: sensorenregister
  env: local
  team: cccssront01

buildMetadata:
- originAnnotations

patches:
- path: deployment.yaml
- path: admin/deployment.yaml
- path: migrate.job.yaml

configMapGenerator:
- behavior: merge
  literals:
  - DEBUG=true
  - SECRET_KEY=dev
  - DATABASE_HOST=database
  - DATABASE_NAME=dev
  - DATABASE_PASSWORD=dev
  - DATABASE_PORT=5432
  - DATABASE_USER=dev
  - OIDC_RP_CLIENT_ID=dev
  - OIDC_RP_CLIENT_SECRET=dev
  name: api-env
- behavior: merge
  literals:
  - DEBUG=true
  - SECRET_KEY=dev
  - DATABASE_HOST=database
  - DATABASE_NAME=dev
  - DATABASE_PASSWORD=dev
  - DATABASE_PORT=5432
  - DATABASE_USER=dev
  - OIDC_RP_CLIENT_ID=dev
  - OIDC_RP_CLIENT_SECRET=dev
  name: admin-env

images:
- name: '*/sensorenregister/api'
  newName: localhost:5001/sensorenregister/api
  newTag: latest
- name: saks01weuacrpgpgo5qvmwo.azurecr.io/sensorenregister/api
  newName: localhost:5001/sensorenregister/api
  newTag: latest
