name: ssr

tenantId: 72fca1b1-2c2e-4376-a445-294d80196804

image:
  registry: saks01weuacrpgpgo5qvmwo.azurecr.io
  repository: sensorenregister/api
  tag: latest

labels:
  app: sensorenregister

network:
  allow-ingress:
    selector: app == 'sensorenregister'
    ingress:
      - action: Allow
    egress:
      - action: Allow

secrets:
  certificate:
    tls: sensorenregister
  backend:
    secrets:
      - secret-key
      - database-host
      - database-name
      - database-user

jobs:
  certificate-init:
    labels:
      component: certificate
    mountSecrets:
      - certificate
    command:
      - bash
    args:
      - -c
      - |
        ls -lah /mnt/secrets/certificate

  migrate:
    labels:
      component: migrate
    volumes:
      - name: tmp
        mountPath: /tmp
        spec:
          emptyDir: {}
    mountSecrets:
      - certificate
    secrets:
      - backend
    command:
      - python
      - manage.py
      - migrate

cronJobs:
  import:
    labels:
      component: import
    schedule: "0 * * * *"
    secrets:
      - backend
    command:
      - python
      - manage.py
      - import_api

deployments:
  api:
    selectorLabels:
      component: api
    env:
      BASE_URL: /api
      ADMIN_ENABLED: false
      API_ENABLED: true
      API_PATH: /
    resources:
      requests:
        cpu: 1
        memory: "512Mi"
      limits:
        cpu: 1
        memory: "512Mi"
    ports:
      - port: 8000
        name: http
    secrets:
      - backend
    volumes:
      - name: tmp
        mountPath: /tmp
        spec:
          emptyDir: {}

  admin:
    selectorLabels:
      component: admin
    env:
      BASE_URL: /admin
      ADMIN_ENABLED: true
      API_ENABLED: false
      ADMIN_PATH: /
    ports:
      - port: 8000
        name: http
    secrets:
      - backend

services:
  api:
    selector:
      component: api
    ports:
      - port: 8000
        targetPort: http
  admin:
    selector:
      component: admin
    ports:
      - port: 8000
        targetPort: http

ingress:
  api:
    className: nginx-external
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        service: api
        port: 8000
    tls:
      certificate: sensorenregister
  admin:
    className: nginx-internal
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    paths:
      - path: /admin(/|$)(.*)
        service: admin
        port: 8000
    tls:
      certificate: sensorenregister
