parameters:
  # job name
  - name: name
    type: string

  # Container registry to work with
  - name: registry
    type: string

  # Service connection to talk to azure
  - name: serviceConnection
    type: string

  # Agent pool to use
  - name: pool
    type: object
    # default: ContainerBuilder
    default:
      vmImage: ubuntu-latest

jobs:
  - job: ${{ parameters.name }}
    pool: ${{ parameters.pool }}
    displayName: Build
    steps:
      - script: echo build
        displayName: build step
