parameters:
  # job name
  - name: name
    type: string
    default: build

  # Container registry to work with
  - name: registry
    type: string

  # Service connection to talk to azure
  - name: serviceConnection
    type: string

  # Agent pool to use
  - name: pool
    type: object
    default: ContainerBuilder

  - name: variables
    type: object
    default: {}

  - name: environment
    type: string

  - name: dependsOn
    type: object
    default: []

  - name: steps
    type: object
    default:
      - script: make test
      - script: make build
      - script: make push

jobs:
  - job: ${{ parameters.name }}
    dependsOn: ${{ parameters.dependsOn }}
    pool: ${{ parameters.pool }}
    displayName: Build
    variables:
      registry: ${{ parameters.registry }}
      version: $(Build.SourceVersion)
      env: ${{ parameters.environment }}
      ${{ insert }}: ${{ parameters.variables}}
    steps:
      - script: env | sort

      # Login using the local system identity
      - script: |
          az login --identity
          az acr login -n $(REGISTRY)

      - ${{ parameters.steps }}
