parameters:
  # job name
  - name: name
    type: string
    default: deploy

  # Container registry to work with
  - name: registry
    type: string

  # Service connection to talk to azure
  - name: serviceConnection
    type: string

  # Agent pool to use
  - name: pool
    type: object
    default:
      vmImage: ubuntu-latest

  - name: dependsOn
    type: object
    default: []

  - name: steps
    type: object
    default: []

jobs:
  - job: ${{ parameters.name }}
    dependsOn: ${{ parameters.dependsOn }}
    pool: ${{ parameters.pool }}
    displayName: Deploy
    steps:
      - ${{ parameters.steps }}
