trigger:
  batch: true
  branches:
    include:
      - main
  tags:
    include:
      - "*.*.*"

variables:
  # Debugging
  System.Debug: true

resources:
  repositories:
    - repository: templates
      type: git
      name: opdrachten/templates
      ref: main

extends:
  template: pipelines/aks/template.yaml@templates
  parameters:
    name: ssr-backend
    dev:
      pool: Opdrachten
      namespace: ns-ccc-opdr-ont-01-sensorenregister
      kubernetesServiceConnection: SCN-K8S-ns-ccc-opdr-ont-01-sensorenregister
      preSteps:
        - script: helm uninstall sensorenregister || true
          displayName: Remove previous installation
        - script: helm uninstall backend || true
          displayName: Remove previous installation
        - script: helm uninstall ssr-backend || true
          displayName: Remove previous installation
    test:
      pool: Opdrachten
      namespace: ns-ccc-opdr-tst-01-sensorenregister
      kubernetesServiceConnection: SCN-K8S-ns-ccc-opdr-tst-01-sensorenregister