trigger:
  batch: true
  branches:
    include:
      - main
  tags:
    include:
      - "*.*.*"

variables:
  # Debugging
  System.Debug: true

resources:
  repositories:
    - repository: templates
      type: git
      name: opdrachten/templates
      ref: main

extends:
  template: pipelines/aks/template.yaml@templates
  parameters:
    name: sensorenregister-backend
    build:
      producedImages:
      - opdrachten/sensorenregister-api-dev
      - opdrachten/sensorenregister-api-test
    dev:
      pool: Opdrachten
      namespace: ns-ccc-opdr-ont-01-sensorenregister
      kubernetesServiceConnection: SCN-K8S-ns-ccc-opdr-ont-01-sensorenregister
      preSteps:
        - script: helm uninstall ssr-backend -n ns-ccc-opdr-ont-01-sensorenregister || true
    test:
      pool: Opdrachten
      namespace: ns-ccc-opdr-tst-01-sensorenregister
      kubernetesServiceConnection: SCN-K8S-ns-ccc-opdr-tst-01-sensorenregister
      preSteps:
        - script: helm uninstall ssr-backend -n ns-ccc-opdr-tst-01-sensorenregister || true
    acc:
      pool: Opdrachten
      namespace: ns-ccc-opdr-acc-01-sensorenregister
      kubernetesServiceConnection: SCN-K8S-ns-ccc-opdr-acc-01-sensorenregister
      preSteps:
        - script: helm uninstall ssr-backend -n ns-ccc-opdr-acc-01-sensorenregister || true
    prod:
      pool: Opdrachten
      namespace: ns-ccc-opdr-prd-01-sensorenregister
      kubernetesServiceConnection: SCN-K8S-ns-ccc-opdr-prd-01-sensorenregister
      preSteps:
        - script: helm uninstall ssr-backend -n ns-ccc-opdr-prd-01-sensorenregister || true