resources:
  repositories:
    - repository: templates
      type: git
      name: mobiliteit/templates
      ref: main

trigger:
  batch: true
  branches:
    include:
      - main
  tags:
    include:
      - "*.*.*"

variables:
  # Debugging
  System.Debug: false

stages:
  - template: status-stage.yaml
