parameters:
  - name: serviceConnection
    type: string

  - name: registry
    type: string
    default: saks01weuacrpgpgo5qvmwo.azurecr.io

  - name: build
    type: object
    default: {}

  - name: deploy
    type: object
    default: {}

jobs:
  - template: build.job.yaml
    parameters:
      name: build
      serviceConnection: ${{ parameters.serviceConnection }}
      registry: ${{ parameters.registry }}

      ${{ if parameters.build.pool }}:
        pool: ${{ parameters.build.pool }}

  - template: deploy.job.yaml
    parameters:
      name: deploy
      serviceConnection: ${{ parameters.serviceConnection }}
      registry: ${{ parameters.registry }}

      ${{ if parameters.deploy.pool }}:
        pool: ${{ parameters.deploy.pool }}
