trigger:
  batch: true
  branches:
    include:
      - main
  tags:
    include:
      - "*.*.*"

parameters:
  # connection
  - name: serviceConnection
    type: string

  - name: registry
    default: saks01weuacrpgpgo5qvmwo.azurecr.io

variables:
  - name: foo
    value: bar

stages:
  - stage: dev
    jobs:
      - template: build.job.yaml
        parameters:
          serviceConnection: ${{ parameters.serviceConnection }}
          registry: ${{ parameters.registry }}
      - template: deploy.job.yaml
        parameters:
          serviceConnection: ${{ parameters.serviceConnection }}
          registry: ${{ parameters.registry }}
