parameters:
  - name: dev
    type: object
    default: {}

  - name: test
    type: object
    default: {}

stages:
  - stage: dev
    jobs:
      - template: template.stage.yaml
        parameters:
          serviceConnection: ${{ parameters.dev.serviceConnection }}
          build: ${{ parameters.dev.build }}
          deploy: ${{ parameters.dev.deploy }}

  - stage: test
    jobs:
      - template: template.stage.yaml
        parameters:
          serviceConnection: ${{ parameters.test.serviceConnection }}
          build: ${{ parameters.test.build }}
          deploy: ${{ parameters.test.deploy }}
