parameters:
  - name: dev
    type: object
    default: {}

  - name: test
    type: object
    default: {}

stages:
  - stage: dev
    jobs:
      - template: template.stage.yaml
        parameters:
          ${{ insert }}: ${{ parameters.dev }}

  - stage: test
    jobs:
      - template: template.stage.yaml
        parameters:
          ${{ insert }}: ${{ parameters.test }}
