parameters:
  - name: serviceConnection
    type: string

  - name: registry
    type: string
    default: saks01weuacrpgpgo5qvmwo.azurecr.io

  - name: build
    type: object
    default: {}

  - name: deploy
    type: object
    default: {}

jobs:
  - template: build.job.yaml
    parameters:
      # Base params
      serviceConnection: ${{ parameters.serviceConnection }}
      registry: ${{ parameters.registry }}

      # Overwrite with user params
      ${{ insert }}: ${{ parameters.build }}

  - template: deploy.job.yaml
    parameters:
      # Base params
      serviceConnection: ${{ parameters.serviceConnection }}
      registry: ${{ parameters.registry }}

      # Overwrite with user params
      ${{ insert }}: ${{ parameters.deploy }}

      dependsOn: build
