parameters:
  - name: dev
    type: object
    default: {}

  - name: test
    type: object
    default: {}

stages:
  - stage: dev
    ${{ if parameters.dev.variables }}:
      variables: ${{ parameters.dev.variables }}
    jobs:
      - template: template.stage.yaml
        parameters:
          ${{ insert }}: ${{ parameters.dev }}
          environment: dev

  - ${{ if parameters.test.serviceConnection }}:
      - stage: test
        ${{ if parameters.test.variables }}:
          variables: ${{ parameters.test.variables }}
        jobs:
          - template: template.stage.yaml
            parameters:
              ${{ insert }}: ${{ parameters.test }}
              environment: test
