{{- $fullName := include "helm.fullname" $ -}}

{{- range $manifestName, $values := .Values.deployments }}
{{- if ne .enabled false }}
{{- $context := dict "local" . "root" $ -}}
{{- $annotations := include "resource.annotations" $context }}
{{- $labels := include "resource.labels" $context }}
{{- $selectorLabels := include "resource.selectorLabels" $context }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $manifestName }}-{{ $fullName }}"
  labels: {{ $labels | nindent 4 }}
  {{- with $annotations }}
  annotations: {{ . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- $selectorLabels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- $labels | nindent 8 }}
    spec:
      restartPolicy: Always
      tolerations: {{- include "pod.tolerations" $ | nindent 8 }}
      securityContext:
        {{- include "pod.securityContext" $context | nindent 8 }}

      containers:
      - name: main
        {{- include "container" $context | indent 8 }}

      {{- with include "pod.volumes" $context }}
      volumes: {{- . | trim | nindent 8}}
      {{- end }}
{{- end }}
{{- end }}
