{{- $root := . -}}
{{- $fullName := include "helm.fullname" $ -}}

{{- range $manifestName, $values := $.Values.ingress }}
{{- if ne $values.enabled false }}

{{- $context := dict "local" . "root" $ -}}
{{- $annotations := include "resource.annotations" $context }}
{{- $labels := include "resource.labels" $context }}
{{- $selectorLabels := include "resource.selectorLabels" $context }}
---

{{/* {{- $svcPort := $values.service.port -}} */}}
{{- if and .className (not (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .annotations "kubernetes.io/ingress.class" .className}}
  {{- end }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $manifestName }}-{{ $fullName }}"
  labels:
    {{- $labels | nindent 4 }}
  {{- with $annotations }}
  annotations: 
    {{- . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .className }}
  {{- if .host }}
  {{- with .tls }}
  tls:
    - hosts:
        - {{ $values.host | quote }}
      secretName: {{ .certificate }}
  {{- end }}
  {{- end }}
  rules:
    - {{ if .host -}}
      host: {{ .host | quote }}
      {{ end -}}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ required "Ingress path needs a service" .service }}
                port:
                  number: {{ .port }}
          {{- end }}

{{- end }}
{{- end }}

