{{- $fullName := include "helm.fullname" $ -}}

{{- range $manifestName, $values := $.Values.jobs }}
{{- if ne .enabled false }}
{{- $context := dict "local" . "root" $ -}}
{{- $annotations := include "resource.annotations" $context }}
{{- $labels := include "resource.labels" $context }}
{{- $selectorLabels := include "resource.selectorLabels" $context }}
---

apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ $manifestName }}-{{ $fullName }}"
  labels: {{ $labels | nindent 4 }}
  {{- with $annotations }}
  annotations: {{ . | nindent 4 }}
  {{- end }}
spec:
  backoffLimit: {{ .backoffLimit | default 5 }}
  template:
    metadata:
      labels:
        {{- $labels | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      tolerations: {{- include "pod.tolerations" $ | nindent 8 }}
      securityContext:
        {{- include "pod.securityContext" $context | nindent 8 }}

      containers:
      - name: main
        {{- include "container" $context | nindent 8 }}
    volumes:
      {{- include "pod.volumes" $context | nindent 6 }}
{{ end }}
{{ end }}
