{{- $fullName := include "helm.fullname" $ }}
{{- $labels := include "helm.labels" $ -}}
{{- range $key, $value := .Values.secrets | default list }}
{{- if $value.enabled | default true }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $key }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    userAssignedIdentityID: "{{ $value.keyVaultIdentity | default $.Values.keyVaultIdentity }}"
    keyvaultName: "{{ $value.keyVaultName | default $.Values.keyVaultName }}"
    tenantId: "{{ $.Values.tenantId }}"
    objects: |
      array:
      {{- range $value.tls | default list }}
        - |
          objectName: {{ . }}
          objectType: secret
      {{- end }}
      {{- range $value.secrets | default list }}
        - |
          objectName: {{ . | upper | replace "-" "_" }}
          objectType: secret
      {{- end }}
  secretObjects:
    - secretName: {{ $key }}
      type: Opaque
      data:
      {{- range $value.tls | default list }}
        - objectName: {{ . }} # must match object name or alias
          key: tls.key
        - objectName: {{ . }} # must match object name or alias
          key: tls.crt
      {{- end }}
      {{- range $value.secrets | default list }}
        - objectName: {{ . }} # must match object name or alias
          key: {{ . }} # must match deployment
      {{- end }}
---
{{- end }}
{{- end }}
