apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  template:
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      initContainers:
        - name: wait
          image: localhost:5000/sensorenregister/api:latest
          command:
            - /app/deploy/wait-for-it.sh
            - database:5432
            - -t
            - "10"
          volumeMounts:
            - mountPath: secrets
              $patch: delete
      volumes:
        - name: secrets
          $patch: delete
