apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: main
          resources:
            limits:
              cpu: 1
              memory: "256Mi"
            requests:
              cpu: 1
              memory: "256Mi"
          # command:
            # - bash
            # - -c
            # - python manage.py runserver_plus --print-sql 0.0.0.0:8000
