apiVersion: batch/v1
kind: CronJob
metadata:
  name: import
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: main
              volumeMounts:
                - mountPath: /secrets
                  $patch: delete
          volumes:
            - name: secrets
              $patch: delete
