resources:
  - ../../base

components:
  - ../../components/api
  - ../../components/database

commonLabels:
  team: cccssront01
  app: sensorenregister
  env: local

buildMetadata:
  - originAnnotations

patchesStrategicMerge:
  - deployment.yaml
  - import.cronjob.yaml
  - migrate.job.yaml

configMapGenerator:
  - name: api-env
    behavior: merge
    envs:
      - api.env

secretGenerator:
  - name: api-secrets
    literals:
      - DEBUG=true
      - SECRET_KEY=dev
      - DATABASE_HOST=database
      - DATABASE_NAME=dev
      - DATABASE_PASSWORD=dev
      - DATABASE_USER=dev
      - OIDC_RP_CLIENT_ID=dev
      - OIDC_RP_CLIENT_SECRET=dev

images:
  - name: localhost:15000/sensorenregister/api
    newName: localhost:15000/sensorenregister/api-dev
    newTag: latest
