bases:
  - ../../base

resources:
  - database.deployment.yaml
  - database.service.yaml
  - nodeport.yaml

commonLabels:
  env: local

configMapGenerator:
  - name: app-env
    behavior: merge
    envs:
      - app.env

patchesStrategicMerge:
  - deployment.yaml
  - migrate.job.yaml
  - import.job.yaml
  - |-
    apiVersion: secrets-store.csi.x-k8s.io/v1
    kind: SecretProviderClass
    metadata:
      name: secrets
    $patch: delete

patches:
  # - target:
  #     kind: Job
  #     name: migrate
  #   patch: |-
  #     - op: add
  #       path: "/spec/template/spec/containers/0/envFrom/-"
  #       value:
  #         secretRef:
  #           name: app-secrets
  #     - op: add
  #       path: "/spec/template/spec/containers/0/envFrom/-"
  #       value:
  #         secretRef:
  #           name: app-secrets
  - target:
      kind: Ingress
      name: app
    patch: |-
      - op: add
        path: "/spec/rules/0/host"
        value: localhost

images:
  - name: localhost:5000/sensorenregister/api
    newName: localhost:5000/sensorenregister/api-dev
    newTag: latest
