resources:
  - ../../base

buildMetadata:
  - originAnnotations

components:
  - ../../components/api
  - ../../components/database

commonLabels:
  team: cccssront01
  app: sensorenregister
  env: local

configMapGenerator:
  - name: api-env
    behavior: merge
    envs:
      - api.env

secretGenerator:
  - name: api-secrets
    literals:
      - DEBUG=true
      - SECRET_KEY=dev
      - DATABASE_HOST=database
      - DATABASE_NAME=dev
      - DATABASE_PASSWORD=dev
      - DATABASE_USER=dev
      - OIDC_RP_CLIENT_ID=dev
      - OIDC_RP_CLIENT_SECRET=dev

patchesStrategicMerge:
  - deployment.yaml

replacements:
  - source:
      kind: Deployment
      name: api
      fieldPath: spec.template.spec.initContainers
    targets:
      - select:
          kind: Job
          labelSelector: component=api
        fieldPaths:
          - spec.template.spec.initContainers
        options:
          create: true

# patches:
#   - target:
#       kind: Ingress
#       name: api
#     patch: |-
#       - op: add
#         path: "/spec/rules/0/host"
#         value: localhost

images:
  - name: localhost:5000/sensorenregister/api
    newName: localhost:5000/sensorenregister/api-dev
    newTag: latest
