resources:
  - ../../base

components:
  - ../../components/api
  - ../../components/admin
  - ../../components/database

commonLabels:
  team: cccssront01
  app: sensorenregister
  env: local

buildMetadata:
  - originAnnotations

patches:
  - path: deployment.yaml
  - path: admin/deployment.yaml
  - path: migrate.job.yaml

secretGenerator:
  - name: app-secrets
    literals:
      - DEBUG=true
      - SECRET_KEY=dev
      - DATABASE_HOST=database
      - DATABASE_NAME=dev
      - DATABASE_PASSWORD=dev
      - DATABASE_PORT=5432
      - DATABASE_USER=dev
      - OIDC_RP_CLIENT_ID=dev
      - OIDC_RP_CLIENT_SECRET=dev

images:
  - name: localhost:5001/sensorenregister/api
    newName: localhost:5001/sensorenregister/api-dev
    newTag: latest
