bases:
  - ../../base

resources:
  - database.deployment.yaml
  - database.service.yaml
  - nodeport.yaml

commonLabels:
  env: local

configMapGenerator:
  - name: app-env
    behavior: merge
    envs:
      - app.env

secretGenerator:
  - name: app-secrets
    envs:
      - secrets.env

patchesStrategicMerge:
  - deployment.yaml
  - migrate.job.yaml
  - import.job.yaml

patches:
  - target:
      kind: Deployment
      name: app
    patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/envFrom/-"
        value:
          secretRef:
            name: app-secrets
  - target:
      kind: Job
      name: migrate
    patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/envFrom/-"
        value:
          secretRef:
            name: app-secrets
      - op: add
        path: "/spec/template/spec/containers/0/envFrom/-"
        value:
          secretRef:
            name: app-secrets

images:
  - name: nginxdemos/hello
    newName: iot-api-dev
    newTag: latest
    # newTag: plain-text
