commonLabels:
  generator: kustomize
  team: cccssront01
  app: sensorenregister
  env: local

labels:
  - pairs:
      team: TAMM
    includeSelectors: false
    includeTemplates: true

resources:
  - ../../base

components:
  - ../../components/app
  - ../../components/database
  - ../../components/ingress
  - ../../components/keyvault

configMapGenerator:
  - name: app-env
    behavior: merge
    envs:
      - app.env

patchesStrategicMerge:
  - deployment.yaml
  - secretproviderclass.yaml

replacements:
  - source:
      kind: Deployment
      name: app
      fieldPath: spec.template.spec.initContainers
    targets:
      - select:
          kind: Job
          labelSelector: component=api
        fieldPaths:
          - spec.template.spec.initContainers
        options:
          create: true

patches:
  - target:
      kind: Ingress
      name: app
    patch: |-
      - op: add
        path: "/spec/rules/0/host"
        value: localhost

images:
  - name: localhost:5000/sensorenregister/api
    newName: localhost:5000/sensorenregister/api-dev
    newTag: latest
