apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    spec:
      containers:
        - name: main
          command:
            - /app/deploy/wait-for-it.sh
            - database:5432
            - -t 30
            - --
            - python
            - manage.py
            - migrate
