apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    spec:
      containers:
        - name: main

          command:
            - /app/deploy/wait-for-it.sh
            - database:5432
            - --
            - sh
            - -c
          args:
            - ./manage.py migrate;
              ./manage.py import_api
          volumeMounts:
            - mountPath: /secrets
              $patch: delete
      volumes:
        - name: secrets
          $patch: delete
