apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets
spec:
  provider: vault
  # secretObjects:
  #   - secretName: app-secrets
  #     type: Opaque
  #     data:
  #       - objectName: oidc-rp-client-id
  #         key: OIDC_RP_CLIENT_ID
  #       - objectName: oidc-rp-client-secret
  #         key: OIDC_RP_CLIENT_SECRET
  parameters:
    vaultAddress: http://vault.default:8200
    roleName: dev
    objects: |
      - secretPath: "secret/data/app"
        objectName: oidc-rp-client-id
        secretKey: oidc-rp-client-id
      - secretPath: "secret/data/app"
        objectName: oidc-rp-client-secret
        secretKey: oidc-rp-client-secret

      - secretPath: "secret/data/app"
        objectName: secret-key
        secretKey: secret-key
      - secretPath: "secret/data/app"
        objectName: debug
        secretKey: debug

      - secretPath: "secret/data/app"
        objectName: postgresql-main-host
        secretKey: postgresql-main-host
      - secretPath: "secret/data/app"
        objectName: postgresql-main-admin
        secretKey: postgresql-main-admin
      - secretPath: "secret/data/app"
        objectName: postgresql-main-password
        secretKey: postgresql-main-admin
      - secretPath: "secret/data/app"
        objectName: postgresql-main-database
        secretKey: postgresql-main-database
