# Default keyvault for getting secrets
keyVaultName: ssr-o-gp4jqffo3heda

# Managed identity (clientId) for workload identity with
workloadIdentity: 0289e90a-b691-4a9b-b747-4d5da9e2b546

image:
  repository: sensorenregister/api-dev

# We must select the nodepool to run the pods on
nodepool: cccssront01

# Default host for the ingress resources
host: ssr-o.azure.amsterdam.nl

# Specify the keyvault that has the certificate
secrets:
  certificate:
    keyVaultName: shared-o-ftytfsr6vuduo

  database:
    type: opaque
    secrets:
      database-host: ssr-o-gp4jqffo3heda.postgres.database.azure.com
      database-name: main
      database-user: ssr-backend-o
