tenantId: 72fca1b1-2c2e-4376-a445-294d80196804  # Global

# Default keyvault for getting secrets
keyVaultName: sensorenregister-o-b2lva  # App specific

# Managed identity (clientId) for workload identity with
workloadIdentity: f48f64e4-bd5f-4331-920b-0a3443343e4f

image:
  repository: opdrachten/sensorenregister-api-dev

# We must select the nodepool to run the pods on
nodepool: cccopdront01  # Environment specific

# Default host for the ingress resources
host: sensorenregister.opdr-o.azure.amsterdam.nl  # App specific

# Specify the keyvault that has the certificate
secrets:
  certificate:
    keyVaultName: shared-o-yhqbd6yktpphi  # Environment specific
  database:
    type: opaque
    secrets:
      database-host: sensorenregister-o-b2lva.postgres.database.azure.com
      database-name: main
      database-user: sensorenregister-app-o

  database:
    type: opaque
    secrets:
      database-host: sensorenregister-o-b2lva.postgres.database.azure.com
      database-name: main
      database-user: sensorenregister-app-o

ingress:
  app:
    className: nginx-internal  # App specific