image:
  registry: localhost:5000
  repository: opdrachten/sensorenregister-api-dev

# Default host for the ingress resources
host: localhost

jobs:
  certificate-init:
    enabled: false

ingress:
  app:
    className: nginx
    tls: null

secrets:
  certificate:
    enabled: false