image:
  registry: localhost:5000
  repository: sensorenregister/api-dev

# Default host for the ingress resources
host: localhost

network:
  allow-ingress:
    enabled: false

jobs:
  certificate-init:
    enabled: false

persistentVolumeClaims:
  data:
    resources:
      requests:
        storage: 1Gi

deployments:
  database:
    labels:
      component: database
    image:
      registry: null
      repository: postgis/postgis
      tag: 14-3.3
    securityContext:
      runAsNonRoot: false
      runAsUser: null
    env:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      PGDATA: /data
    volumes:
      - name: data
        persistentVolumeClaim: data
    containers:
      - name: main
        securityContext:
          readOnlyRootFilesystem: false
        volumes:
          - name: data
            mountPath: /data

services:
  database:
    selector:
      component: database
    ports:
      - port: 5432
        targetPort: 5432

ingress:
  backend-external:
    enabled: false
  backend-internal:
    className: nginx
    tls: null

secrets:
  certificate:
    enabled: false
  backend:
    type: opaque
    secrets:
      secret-key: dev
      database-host: database-backend
      database-name: dev
      database-user: dev
      oidc-base-url: dev
      oidc-rp-client-id: dev
      oidc-rp-client-secret: dev
      applicationinsights-connection-string: ""
