tenantId: 72fca1b1-2c2e-4376-a445-294d80196804  # Global

# Default keyvault for getting secrets
keyVaultName: sensorenregister-t-kbroh  # App specific

# Managed identity (clientId) for workload identity with
workloadIdentity: 2c3043ce-bc3d-4358-9c0c-6220105d7574

image:
  repository: opdrachten/sensorenregister-api

# We must select the nodepool to run the pods on
nodepool: cccopdrtst01  # Environment specific

# Default host for the ingress resources
host: sensorenregister.opdr-t.azure.amsterdam.nl  # App specific

# Specify the keyvault that has the certificate
secrets:
  certificate:
    keyVaultName: shared-t-ddxsibl3lrdai  # Environment specific
  database:
    type: opaque
    secrets:
      database-host: sensorenregister-t-kbroh.postgres.database.azure.com
      database-name: main
      database-user: sensorenregister-app-t

ingress:
  app:
    className: nginx-internal  # App specific