# Default keyvault for getting secrets
keyVaultName: ssr-t-zryvqlwvrfmge

# Managed identity (clientId) for workload identity with
workloadIdentity: 2c3043ce-bc3d-4358-9c0c-6220105d7574

image:
  repository: opdrachten/sensorenregister-api-dev

# We must select the nodepool to run the pods on
nodepool: cccssrtst01

# Default host for the ingress resources
host: sensorenregister.opdr-t.azure.amsterdam.nl

# Specify the keyvault that has the certificate
secrets:
  certificate:
    keyVaultName: shared-t-ddxsibl3lrdai

  database:
    type: opaque
    secrets:
      database-host: ssr-t-zryvqlwvrfmge.postgres.database.azure.com
      database-name: main
      database-user: ssr-backend-t
