apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000

      automountServiceAccountToken: false

      containers:
        - name: main
          image: localhost:5000/sensorenregister/api:latest
          imagePullPolicy: Always # IfNotPresent
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 1
              memory: "512Mi"
            limits:
              cpu: 1
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: api-env
            - secretRef:
                name: api-secrets
          volumeMounts:
            - mountPath: /secrets
              name: secrets
              readOnly: true
      volumes:
        - name: secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: secrets
