apiVersion: batch/v1
kind: CronJob
metadata:
  name: import
  labels:
    component: import
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 6
  jobTemplate:
    spec:
      backoffLimit: 5
      template:
        metadata:
          labels:
            component: import
        spec:
          restartPolicy: Never
          containers:
            - name: main
              image: saks01weuacrpgpgo5qvmwo.azurecr.io/sensorenregister/api:latest
              imagePullPolicy: Always # IfNotPresent
              command:
                - python
                - manage.py
                - import_api

              securityContext:
                privileged: false
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true

              envFrom:
                - configMapRef:
                    name: api-env
              volumeMounts:
                - name: tmp
                  mountPath: /tmp
          volumes:
            - name: tmp
              emptyDir: {}
