apiVersion: batch/v1
kind: CronJob
metadata:
  name: import
  labels:
    component: import
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            component: import
        spec:
          restartPolicy: Never
          containers:
            - name: main
              image: localhost:15000/sensorenregister/api:latest
              imagePullPolicy: Always # IfNotPresent
              command:
                - python
                - manage.py
                - import_api

              securityContext:
                privileged: false
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true

              envFrom:
                - configMapRef:
                    name: api-env
                - secretRef:
                    name: app-secrets

          volumes:
            - name: secrets
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: secrets
