apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  labels:
    component: migrate
spec:
  backoffLimit: 15
  template:
    metadata:
      labels:
        component: migrate
    spec:
      restartPolicy: Never
      containers:
        - name: main
          image: saks01weuacrpgpgo5qvmwo.azurecr.io/sensorenregister/api:latest
          imagePullPolicy: Always # IfNotPresent
          command:
            - python
            - manage.py
            - migrate

          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true

          envFrom:
            - configMapRef:
                name: api-env
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
