apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  labels:
    component: migrate
spec:
  backoffLimit: 15
  template:
    metadata:
      labels:
        component: migrate
    spec:
      restartPolicy: Never
      containers:
        - name: main
          image: localhost:5001/sensorenregister/api:latest
          imagePullPolicy: Always # IfNotPresent
          command:
            - python
            - manage.py
            - migrate

          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true

          envFrom:
            - configMapRef:
                name: api-env
            - secretRef:
                name: app-secrets

      volumes:
        - name: secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: secrets
