apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
        version: "1"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000

      automountServiceAccountToken: false

      tolerations:
        - key: "foo"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"

      containers:
        - name: main
          image: localhost:5000/sensorenregister/api:latest
          imagePullPolicy: Always # IfNotPresent
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 1
              memory: "512Mi"
            limits:
              cpu: 1
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: app-env
            - secretRef:
                name: app-secrets
          volumeMounts:
            - mountPath: /config
              name: config
              readOnly: true
            - mountPath: /secrets
              name: secrets
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: app-config
        - name: secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: secrets
