apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  labels:
    component: api
spec:
  backoffLimit: 9
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: main
          image: localhost:5000/sensorenregister/api:latest
          imagePullPolicy: IfNotPresent
          command:
            - python
            - manage.py
            - migrate
