apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets
spec:
  provider: azure
  secretObjects:
    - secretName: secrets
      type: kubernetes.io/tls
      labels:
        app: sensorenregister
      data: []
    - secretName: certificate
      type: kubernetes.io/tls
      labels:
        app: sensorenregister
      data:
        - objectName: sensorenregister
          key: tls.key
        - objectName: sensorenregister
          key: tls.crt

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "00000000-0000-0000-0000-000000000000"
    keyvaultName: my-kv
    objects: |
      array:
        - |
          objectName: sensorenregister
          objectType: secret
    tenantId: "00000000-0000-0000-0000-000000000000" # The tenant ID of the key vault
