# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets
spec:
  provider: azure
  secretObjects:
    - secretName: tls
      type: kubernetes.io/tls
      labels:
        app: sensorenregister
      data:
        - objectName: sensorenregister
          key: tls.key
        - objectName: sensorenregister
          key: tls.crt
    - secretName: app-secrets
      type: Opaque
      labels:
        app: sensorenregister
      data:
        - objectName: oidc-rp-client-id
          key: oidc-rp-client-id
        - objectName: oidc-rp-client-secret
          key: oidc-rp-client-secret
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: main-weu-o-yh7oqq4sbyjt
    objects: |
      array:
        - |
          objectName: sensorenregister
          objectType: secret
        - |
          objectName: oidc-rp-client-id
          objectType: secret
        - |
          objectName: oidc-rp-client-secret
          objectType: secret
    tenantId: "72fca1b1-2c2e-4376-a445-294d80196804" # The tenant ID of the key vault
