# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets
spec:
  provider: azure
  secretObjects:
    - secretName: tls
      type: kubernetes.io/tls
      labels:
        app: sensorenregister
      data:
        - objectName: sensorenregister
          key: tls.key
        - objectName: sensorenregister
          key: tls.crt
    - secretName: app-secrets
      type: Opaque
      labels:
        app: sensorenregister
      data:
        - objectName: oidc-rp-client-id
          key: OIDC_RP_CLIENT_ID
        - objectName: oidc-rp-client-secret
          key: OIDC_RP_CLIENT_SECRET
        - objectName: secret-key
          key: SECRET_KEY
        - objectName: debug
          key: DEBUG
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "00d77036-c127-4b38-a581-f170b55d65f0"
    keyvaultName: main-weu-o-yh7oqq4sbyjt
    objects: |
      array:
        - |
          objectName: sensorenregister
          objectType: secret
        - |
          objectName: oidc-rp-client-id
          objectType: secret
        - |
          objectName: oidc-rp-client-secret
          objectType: secret
        - |
          objectName: secret-key
          objectType: secret
        - |
          objectName: debug
          objectType: secret
    tenantId: "72fca1b1-2c2e-4376-a445-294d80196804" # The tenant ID of the key vault
