# Generated by Django 2.1.2 on 2018-10-25 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='frequency',
            field=models.CharField(choices=[('continuous', 'Continue'),
                                            ('periodic', 'Periodiek'),
                                            ('Incidental', 'Incidenteel')],
                                   max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='in_use_since',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='installation_point',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='organisation',
            field=models.CharField(max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='permit',
            field=models.BooleanField(null=True, blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='owner', to='iot.Person'),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='iot.Type'),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.AddField(
            model_name='device',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='contact', to='iot.Person'),
        ),
    ]
