# Generated by Django 2.1.2 on 2018-10-29 10:43

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_auto_20181025_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='device',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='device',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='device',
            name='type',
        ),
        migrations.AddField(
            model_name='device',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[
                ('CMR', 'Camera'), ('SCP', 'Sensor'), ('SBN', 'Baken'), ('SCG', 'Slimme laadpaal'),
                ('STI', 'Slimme verkeersinformatie'), ('SLP', 'Slimme lantaarnpaal')],
                                                              max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='types',
            field=models.ManyToManyField(blank=True, null=True, to='iot.Type'),
        ),
        migrations.AddField(
            model_name='person',
            name='organisation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='address',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='iot.Address'),
        ),
        migrations.AlterField(
            model_name='device',
            name='contact',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='contact', to='iot.Person'),
        ),
        migrations.AlterField(
            model_name='device',
            name='in_use_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='owner', to='iot.Person'),
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='iot.Location'),
        ),
    ]
