# Generated by Django 3.2.9 on 2021-12-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0009_introduce_new_models_loosely_based_on_sensrnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='is_other',
            field=models.BooleanField(default=True, verbose_name='Anders, namelijk'),
        ),
        # Assume that all themes added until now are standard (they can only come from iprox
        # formula)
        migrations.RunSQL("UPDATE iot_theme SET is_other=FALSE")
    ]
