# Generated by Django 3.2.14 on 2022-07-15 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0014_person_website_as_text_rather_than_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
