# Generated by Django 3.2.14 on 2022-07-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0015_auto_20220715_1110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Device2',
            new_name='Device',
        ),
        migrations.RenameModel(
            old_name='Person2',
            new_name='Person',
        ),
        migrations.RenameModel(
            old_name='Type2',
            new_name='Type',
        ),
    ]
