# Generated by Django 3.2.15 on 2022-08-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0016_auto_20220715_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceJson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themes', models.JSONField()),
                ('observation_goals', models.JSONField()),
                ('project_paths', models.JSONField()),
                ('regions', models.JSONField()),
                ('owner', models.JSONField()),
                ('location', models.JSONField()),
                ('active_until', models.DateField()),
                ('contains_pi_data', models.BooleanField()),
                ('datastream', models.TextField()),
                ('location_description', models.TextField()),
                ('reference', models.TextField()),
                ('type', models.TextField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
